<?php

namespace App\Http\Controllers;

use App\Models\BlogModels;
use Illuminate\Http\Request;

class BlogController extends Controller
{
    //

    private $model;

    public function __construct()
    {
        $this->model= new BlogModels();

        // parent::__call($method, $parameters); // TODO: Change the autogenerated stub
    }

    public function index_blog($blog_name)
    {
        //
    }
}
