<?php

namespace App\Http\Controllers;

use App\Models\IndexModels;
use Illuminate\Http\Request;

 class IndexController extends Controller
{

    private $model;

    public function __construct()
    {
        $this->model= new IndexModels();

       // parent::__call($method, $parameters); // TODO: Change the autogenerated stub
    }


    public function index()
    {
            $categories=$this->model->category();
            $subcategories=$this->model->subcategory();
            $ppk=$this->model->ppk();
            $trendingProducts=$this->model->trending($cat='naziv',$col='');
            $hotItem=$this->model->hot();
            $blog=$this->model->blog();
            $take=3;
            $advert1=$this->model->adverts($start=0,$take);
            $advert2=$this->model->adverts($start=3,$take);
//dd($categories);
            return view('elektrikus',
                [
                    'categories'=>$categories,
                    'subcategories'=>$subcategories,
                    'ppk'=>$ppk,
                    'trendingProducts'=>$trendingProducts,
                    'hotItem'=>$hotItem,
                    'blog'=>$blog,
                    'advert1'=>$advert1,
                    'advert2'=>$advert2
                ]
            );

    }
   public function change_trending(Request $request)
   {

    $category=explode('#',$request->category);
//dd($request->category);
    $trendingProducts=$this->model->trending($category[1],$col='');

    if(count($trendingProducts)>0) {
        return view('ajax.trending_ajax', [
            "trendingProducts" => $trendingProducts
        ]);
    }
    if(count($trendingProducts)==0 || count($trendingProducts)==null)
    {
        return ($data=404);
    }


   }

public function email_subscribe(Request $request)
{
    $email=$request->email;

    $request->validate([
       'email'=> 'unique:subscribe'
    ]);


    $subscribe=$this->model->subscribe($email);


    return ($subscribe);


}

public function search_subcategory()
{
    $subcategory=$this->model->subcategory();

    //dd($subcategory);

    return($subcategory);
}


}
