<?php

namespace App\Http\Controllers;

use App\Models\ProductModels;
use Illuminate\Http\Request;

class ProductController extends Controller
{
    //

    private $model;

    public function __construct()
    {
        $this->model= new ProductModels();

        // parent::__call($method, $parameters); // TODO: Change the autogenerated stub
    }

    public function index(Request $request)
    {
        //
        $category=$request->get('kategorija');
        $string=$request->get('proizvod');
       $prodcut_id=explode('_',$string);
//dd($prodcut_id);
        $data=$this->model->getInformation($prodcut_id[1]);
dd($data);
       return view('single',[
          'data'=>$data

       ]);

    }
}
