<?php

namespace App\Http\Controllers;

use App\Models\IndexModels;
use App\Models\ProductModels;
use App\Models\UserModels;
use Illuminate\Http\Request;

class ProductController extends Controller
{
    //

    private $model;
    private $userModel;
    private $modelIndex;

    public function __construct()
    {
        $this->model= new ProductModels();
        $this->userModel= new UserModels();
        $this->modelIndex=new IndexModels();

        // parent::__call($method, $parameters); // TODO: Change the autogenerated stub
    }

    public function index(Request $request)
    {
        //
        $category=$request->get('kategorija');
        $string=$request->get('proizvod');
       $prodcut_id=explode('el_',$string);

//dd($prodcut_id);
        $data=$this->model->getInformation($prodcut_id[1]);
        $picture=$this->userModel->getPicture($prodcut_id[1]);
//dd($data[0]->price_status);
        switch ($data[0]->price_status)
    {
        case 1:
            $data[0]->price_status='Cena je fiksna';
            break;
        case 2:
            $data[0]->price_status='Moguć dogovor';
            break;
        case 3:
            $data[0]->price_status='Moguća zamena';
            break;
        case 5:
            $data[0]->price_status='Moguć je dogovor ili zamena';
            break;
    }
        switch ($data[0]->condition_status)
        {
            case 1:
                $data[0]->condition_status='Novo';
                break;
            case 2:
                $data[0]->condition_status='Kao novo';
                break;
            case 3:
                $data[0]->condition_status='Polovno';
                break;

        }

        $data[0]->timestamp=date('d.m.Y. H:i:s',$data[0]->timestamp);
        $data[0]->created_at=date('d.m.Y. H:i:s',$data[0]->created_at);

        $categoryList = $this->modelIndex->subcategory();
        $ppk = $this->modelIndex->ppk();
       return view('single',[
          'data'=>$data,
           'picture'=>$picture,
           'categoryList'=>$categoryList,
           'ppk'=>$ppk

       ]);

    }

    public function firstMessage(Request $request)
    {
        $id=auth()->user()->id;
        $text=$request->text;
        $string=$request->href;

        $prodcut_id=explode('el_',$string);
//$product_id[1];
        //dd($prodcut_id);





    }


}
