<?php

namespace App\Http\Controllers;

use App\Models\BaseUserModels;

use App\Models\User;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Validator;
use Illuminate\Http\Request;

class RegisterController extends Controller
{
    //
    private $model;


    public function __construct()
    {
      //  parent::__call($method, $parameters); // TODO: Change the autogenerated stub
        $this->model= new BaseUserModels();
    }

    public function register(Request $request)
    {
        $validator = Validator::make($request->all(), [
            'first_name' => ['required', 'string', 'max:255'],
            'email' => ['required', 'string', 'email', 'max:255', 'unique:users'],
            'username' => ['required', 'string', 'max:20', 'unique:users'],
            'password' => ['required', 'string', 'min:8', 'confirmed'],
        ]);

        if ($validator->passes()) {

            $code=time().$request->email;
            $email_verified_at=Hash::make($code);
          $user=$this->model->create($request->all(),$email_verified_at);

          if($user)
          {


              //
              //mejl slanje
             // dd($user);

              MailController::SendMailSignupEmail($request->first_name, $request->email, $email_verified_at);
          }

        }
        return response()->json(['error'=>$validator->errors()->all()]);



        }


    public function verifyEmail(Request $request)
    {
        $verication_code = $request->get('code');
        $user = User::where([
            ['email_verified_at', '=', $verication_code],
            ['is_Active', '=', '0']
        ])
            ->first();

        if ($user != null) {
            //dd($user);
            $t = time();
//dd($t);


            $user->is_Active = 1;
            $user->email_verified_at = $t;
            $user->save();

            return redirect()->route('/')->with('message', 'Uspesno ste verifikovali nalog!');
        }

    else
        {
            return redirect()->route('/')->with('message', 'Vas nalog je već verifikovan');

        }

    }

}
