<?php

namespace App\Http\Controllers;

use App\Models\IndexModels;
use App\Models\ShopModels;
use Illuminate\Http\Request;

class ShopController extends Controller
{
    private $model;
    private $model1;
   private $start=0;
   private $take=2;
   private $min=null;
   private $max=null;
   private $search=null;
    public function __construct()
    {

        $this->model= new ShopModels();
        $this->model1= new IndexModels();

        // parent::__call($method, $parameters); // TODO: Change the autogenerated stub
    }


    public function index(Request $request)
    {

//dd($request);
        //$cat = $category;
        $cat = $request->get('category');
      //first in main plan
        $hotItemCategory = $this->model1->trending($cat,$col='shop');
        $sort=$this->sorted($sort='default');
        $products = $this->model->oglasi($this->start,$this->take,$cat,$this->min,$this->max,$this->search,$sort);
        //first sponsored iphone

        $categoryList = $this->model1->subcategory();
        $ppk = $this->model1->ppk();
        $count_product=$this->model->pages($cat,$this->min,$this->max,$this->search);
       //number_pages/take
        $pages=ceil($count_product/$this->take);
        if (isset($request->change)) {
           // dd($request->change);
            //ajax

            return  count($products)>0 ?  view('ajax.shop_ajax', ["products" => $products]) : ($data=404) ;



        } else {
            return view('store',
                [
                    'hotItem' => $hotItemCategory,
                    'products' => $products,
                    'categoryList' => $categoryList,
                    'ppk' => $ppk,
                    "pages"=>$pages

                ]);

        }

    }
    public function change_price_filter(Request $request)
    {
        $this->min=$request->min;
        $this->max=$request->max;
        $cat=$request->cat;


        $count=$this->model->countAds($this->min,$this->max,$cat,$this->search);
//dd($count);
        if (!$count>0)
        {
            $count=404;
        }

return($count);

    }

    public function price_filter_shop(Request $request)
    {
        $this->min=$request->min;
        $this->max=$request->max;
        $cat=$request->cat;
$this->start=$request->start;
$this->take=$request->take;

$sort=$this->sorted($sort='default');

        $products=$this->model->oglasi($this->start,$this->take,$cat,$this->min,$this->max,$this->search,$sort);

//dd(count($products));

        return  count($products)>0 ?  view('ajax.shop_ajax', ["products" => $products]) : ($data=404) ;


    }
public function pagination(Request $request)
{
    //
    $this->min=$request->min;
    $this->max=$request->max;
    $cat=$request->cat;
    $this->start=$request->start;
    $this->take=$request->take;

    if(strpos($cat,'#'))
    {
        $string=explode('#',$cat);
        $cat=$string[0];

    }


    $number_page=$this->model->pages($cat,$this->min,$this->max,$this->search);

    if(!$number_page>0)
    {
        $number_page=404;
    }
    else{
        $number_page=ceil($number_page/$request->take);
    }

return ($number_page);

}
public function new_page(Request $request)
{
    $this->min=$request->min;
    $this->max=$request->max;
    $cat=$request->cat;
    $this->start=$request->start;
    $this->take=$request->take;


if(strpos($cat,'#'))
{
    $string=explode('#',$cat);
    $cat=$string[0];
    //dd($cat);
}
$sort=$this->sorted($request->sort);

    $products=$this->model->oglasi($this->start,$this->take,$cat,$this->min,$this->max,$this->search,$sort);

//dd($products);

    return  count($products)>0 ?  view('ajax.shop_ajax', ["products" => $products]) : ($data=404) ;


}

public function sponsored(Request $request)
{

    $cat=$request->category;

    if(strpos($cat,'#'))
    {
        $string=explode('#',$cat);
        $cat=$string[0];

    }

    $products = $this->model1->trending($cat,$col='shop');

    return  count($products)>0 ?  view('ajax.shop_ajax', ["products" => $products]) : ($data=404) ;
}


public function sorted($sort)
{
    $sorted=[];
    switch ($sort)
    {
        case 0:
            array_push($sorted,'id_oglas');
            array_push($sorted,'desc');
            break;
        case 1:
            array_push($sorted,'id_oglas');
            array_push($sorted,'asc');
            break;
        case 2:
            array_push($sorted,'price');
            array_push($sorted,'asc');
            break;
        case 3:
            array_push($sorted,'price');
            array_push($sorted,'desc');
            break;
        default:
            array_push($sorted,'id_oglas');
            array_push($sorted,'desc');
    }
    return $sorted;
}

}
